### PR TITLE
[#201] Extract authentication token 

### PR DESCRIPTION
**Pull request by ruslankhaertdinov**
Related to: https://github.com/fs/rails-base-api/issues/201

### CODE REVIEW

**Comment by ArturMinnullin** [comment]
🔥🆗🔥

**Comment by ruslankhaertdinov** [comment]
@timurvafin please take a look

**Comment by timurvafin** [comment]
@ruslankhaertdinov could you please sync your branch with master?

**Comment by ruslankhaertdinov** [comment]
@timurvafin sure

**Comment by ruslankhaertdinov** [comment]
@timurvafin done

**Pull request merged**
