### PR TITLE
Added health check gem and configuration for him

### PR DESCRIPTION
**Pull request by IlkhamGaysin**
Added health check for api server that will check state of our app and let us know if something was wrong with him.
Also it will give us the opportunity to keep the server in awake mode.

### CODE REVIEW

**Comment by IlkhamGaysin** [comment]
@timurvafin Please review.

**Comment by ruslankhaertdinov** [comment]
@IlkhamGaysin I'm not `Timur Vafin`, but PR looks good! 👍

**Comment by IlkhamGaysin** [comment]
@ruslankhaertdinov Thanks 🍺

**Comment by timurvafin** [comment]
@IlkhamGaysin could your branch

**Comment by IlkhamGaysin** [comment]
Done @timurvafin

**Pull request merged**
