### PR TITLE
Update Rails to 4.2.7.1

### PR DESCRIPTION
**Pull request by ruslankhaertdinov**
Update `Rails` to 4.2.7.1 to fix [Unsafe Query Generation Risk in Active Record](https://groups.google.com/forum/#!topic/rubyonrails-security/rgO20zYW33s) and [Possible XSS Vulnerability in Action View](https://groups.google.com/forum/#!topic/rubyonrails-security/I-VWr034ouk)

### CODE REVIEW

**Comment by ruslankhaertdinov** [comment]
@timurvafin please take a look

**Comment by IlkhamGaysin** [comment]
@ruslankhaertdinov I've also upgraded rails in my one of projects and after that i was getting deprecation warning like: 
``DEPRECATION WARNING: Sprockets method `register_engine` is deprecated.``

Are you getting this error after upgrade?

**Comment by ruslankhaertdinov** [comment]
@IlkhamGaysin I see thes warnings in the projects with `sprocket` related gems (like `autoprefixer-rails` or `sass-rails`). In `rails-base-api` I don't see this one.

**Comment by IlkhamGaysin** [comment]
@ruslankhaertdinov oh yeah it's ``rails-base-api`` app but it is't ``rails-base`` app. Then all looks good. 👍

**Pull request merged**
