### PR TITLE
Use bin/setup instead of bin/bootstrap

### PR DESCRIPTION
**Pull request by maximlarionov**
https://github.com/fs/rails-base-api/issues/166

### CODE REVIEW

**Comment by timurvafin** [comment]
@maximlarionov please find inspiration here https://github.com/fs/rails-base/blob/master/bin/setup

**Comment by maximlarionov** [comment]
@timurvafin you mean, update rails-base bin/setup to look like bin/setup in rails-base-api?

**Comment by vast** [comment]
@maximlarionov, exactly, they share the same logic

**Comment by vast** [comment]
:+1:

**Pull request merged**
