### PR TITLE
Update rails to 4.2.8, update ruby to 2.3.3

### PR DESCRIPTION
**Pull request by ruslankhaertdinov**
Fix failed CI builds

### CODE REVIEW

**Comment by ruslankhaertdinov** [comment]
@timurvafin please review

**Comment by ruslankhaertdinov** [comment]
@timurvafin please take a look

**Comment by ruslankhaertdinov** [comment]
@timurvafin `master` steel broken, please merge this fix if everything is fine

**Comment by timurvafin** [comment]
@ruslankhaertdinov thank you for your work!

**Pull request merged**
